# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'

# Header
language: r
sudo: required
dist: xenial
cache: packages
latex: false

#env
env:
  global:
  - MAKEFLAGS="-j 2"

matrix:
  include:
  - r: release
  after_success:
      - Rscript -e 'covr::codecov()'
      - find . -name testthat.Rout | xargs cat
      after_failure:
      - find . -name testthat.Rout | xargs cat
      before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
  - r: oldrel
  - r: devel

warnings_are_errors: true

#services:
