# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

r:
- 3.3
- oldrel
- release
- devel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libnetcdf-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE); lintr::lint_package()'
