# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'install.packages(c("lintr"))'
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - R -q -e 'covr::codecov(); lintr::lint_package()'

# Header
language: r
sudo: required
dist: xenial
cache: packages
latex: false

#env
env:
  global:
  - MAKEFLAGS="-j 2"

matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel

warnings_are_errors: true

#services:
